name: build-docker
run-name: ${{ github.actor }} is building docker image
on: [push]
jobs:
  push_to_github_packages:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v3
#       -
#         name: Login to GitHub Packages
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
         name: Push to GitHub Packages
        uses: docker/build-push-action@v4
        with:
          push: true
#           username: ${{ github.actor }}
#           password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
#           path: complex/backend
          repository: ${{ github.repository }}
          tags: ["latest"]